---
title: "Simulation results for the causal discovery of DEGs"
author: "Yongjin Park"
---

```{r include = FALSE}
library(data.table)
library(tidyverse)
library(patchwork)
source("R/Util-rmd.R")

fig.dir = 'Fig/Simulation/'

dir.create(fig.dir, recursive = TRUE, showWarnings = FALSE)
knitr::opts_chunk$set(fig.path = fig.dir, fig.width = 6, fig.height = 4)
knitr::opts_chunk$set(dev.args = list(bg = "transparent"), echo = FALSE)
options(stringsAsFactors = FALSE)
```

```{r include = FALSE}
.read <- function(hdr) {
  .files <- list.files(hdr %&% "/result/",
                       pattern = "eval", full.names=TRUE)

  .dat <- lapply(.files, fread, header=T) %>%
    do.call(what=rbind) %>%
    mutate(p1 = as.numeric("0." %&% p1)) %>% 
    mutate(pa = as.numeric("0." %&% pa)) %>% 
    mutate(p0 = as.numeric("0." %&% p0))
}

read.power <- function(hdr, fdr.cutoff = .1) {

  .dat <- .read(hdr)
  .ret <- .dat[order(.dat$power, decreasing=TRUE)]
  .ret <- .ret[fdr <= fdr.cutoff, head(.SD, 1),
               by = .(p1, p0, pa, rseed, method)]

  .ret[, fdr.cutoff := fdr.cutoff]

  return(.ret)
}

read.f1 <- function(hdr) {

  .dat <- .read(hdr)
  .ret <- .dat[order(.dat$f1, decreasing=TRUE)]
  .ret <- .ret[, head(.SD, 1),
               by = .(p1, p0, pa, rseed, method)]

  return(.ret)
}

.rename <- function(.sum) {

  .method <- c("opt","cocoa","marg")
  .lab <- c("optimal", "CoCoA", "marginal")
  .sum[, method := factor(method, .method, .lab)]

  .pa <- sort(unique(.sum$pa))
  .pa.lab <- "X to W (" %&% round(.pa * 100) %&% "%)"
  .sum[, pa := factor(pa, .pa, .pa.lab)]

  return(.sum)
}

.ggplot <- function(...) {
  .scale.x <-
    scale_x_continuous("% variance explained by phenotype (W)",
                       labels=function(x) round(100 * x))
  ggplot(...) +
    theme_bw() +
    theme(strip.text = element_text(size=8)) +
    theme(legend.text = element_text(size=8)) +
    theme(legend.title = element_text(size=6)) +
    scale_linetype_manual(values=c(3, 1, 2))+
    .scale.x    
}

plot.power <- function(.dt) {

  .sum <- .dt[, .(y = mean(power), y.se = sd(power)/sqrt(.N)),
              by = .(p1, p0, pa, method, fdr.cutoff)]

  .cutoff <- min(.sum$fdr.cutoff)

  .sum <- .rename(.sum)

  .aes <- aes(x = p1, y = y, ymin = y - y.se, ymax = y + y.se, lty = method)

  .ggplot(.sum, .aes) +
    facet_wrap(~pa, nrow=1, scales="free") +
    ylab("power at FDR < " %&% .cutoff) +
    geom_line() +
    geom_linerange(lty=1)
}

plot.f1 <- function(.dt) {

  .sum <- .dt[, .(y = mean(f1), y.se = sd(f1)/sqrt(.N)),
              by = .(p1, p0, pa, method)]

  .sum <- .rename(.sum)

  .aes <- aes(x = p1, y = y, ymin = y - y.se, ymax = y + y.se, lty = method)

  .ggplot(.sum, .aes) +
    facet_wrap(~pa, nrow=1, scales="free") +
    ylab("F1 score in PR curve") +
    geom_line() +
    geom_linerange(lty=1)
}
```

## CoCoA improves statistical power


```{r fig.width=6, fig.height=5}
p1 <- plot.f1(read.f1("sim_N40_M50")) + ggtitle("50 cells per individual")
p2 <- plot.f1(read.f1("sim_N40_M10")) + ggtitle("10 cells per individual")
plt <- p1/p2
print(plt)
.file <- fig.dir %&% "/Fig_Sim_F1.pdf"
.gg.save(.file, plot=plt, width=6, height=5)
```

```{r results="asis"}
cat("[PDF](" %&% .file %&% ")\n\n")
```

```{r fig.width=6, fig.height=5}
p1 <- plot.power(read.power("sim_N40_M50")) + ggtitle("50 cells per individual")
p2 <- plot.power(read.power("sim_N40_M10")) + ggtitle("10 cells per individual")
plt <- p1/p2
print(plt)
.file <- fig.dir %&% "/Fig_Sim_Power.pdf"
.gg.save(.file, plot=plt, width=6, height=5)
```

```{r results="asis"}
cat("[PDF](" %&% .file %&% ")\n\n")
```

## CoCoA controls false discovery rates


```{r include = FALSE}
read.efdr <- function(hdr) {
    .dat <- .read(hdr)
    .dat[,
         .(efdr = mean(efdr), efdr.sd = sd(efdr)),
         by = .(target, p0, pa, method)]
}    

hdr <- "null_N40_M50"
efdr.dt <- read.efdr(hdr)
```

```{r fig.width=4, fig.height=5}
.dt <- efdr.dt
.aes <- aes(x = 100 * p0, y = efdr, ymin=pmax(efdr-efdr.sd, 0), ymax=pmin(efdr+efdr.sd, 1))

plt <-
    .gg.plot(.dt[method == "cocoa"], .aes) +
    ylab("empirical FDR") +
    xlab("% variance explained by confounding effect") +
    facet_grid(target ~ pa, scale="free") +
    geom_hline(aes(yintercept = target), colour="red", lty=2, size=.2) +
    geom_bar(stat="identity", fill="#000099", width=10) +
    geom_errorbar(width=3, size=.3)

.file <- fig.dir %&% "/Fig_Sim_FDR.pdf"
.gg.save(.file, plot=plt, width=4, height=5)
print(plt)
```

```{r results="asis"}
cat("[PDF](" %&% .file %&% ")\n\n")
```
